### ISSUE TITLE
Suspicious line of code - data leakage / wrong calculation

### ISSUE THREAD

**Issue by NatanBagrov** [Vanint/PPN#2]
Dear @Vanint and colleagues,

I went through the code, and the paper, and found [this line](https://github.com/Vanint/PPN/blob/master/pgportfolio/marketdata/globaldatamatrix.py#L85):
```python
features=['open','high','low','close']
```

Taken from `/master/pgportfolio/marketdata/globaldatamatrix.py` (line 85):
```python
def get_global_panel(self, start, end, period=300, features=('close',)):
        # comments and code...
        df = pd.read_csv('./database/all_stocks_5yr.csv')
        name_list = df['Name']
        coins = name_list.drop_duplicates(keep='first',inplace=False).tolist()
        self.__coins = coins 
        time = df['date']
        time_index=time.drop_duplicates(keep='first',inplace=False).tolist()
        #for coin in coins:
        #    self.update_data(start, end, coin)  # update data

        if len(coins)!=self._coin_number:
            raise ValueError("the length of selected coin (%d) is not equal to expected %d"
                             % (len(coins), self._coin_number))

        logging.info("feature type list is %s" % str(features))
        self.__checkperiod(period)  # check whether the period belongs to the required ranges
        features=['open','high','low','close']  # <-- THIS IS THE LINE
        #time_index = pd.to_datetime(list(range(start, end+1, period)),unit='s')  
        panel = pd.Panel(items=features, major_axis=coins, minor_axis=time_index, dtype=np.float32)
        # more code...
```

This method is called upon loading the data. However, it is originally called with the following parameters: `features = ['close', 'high', 'low', 'open']`. **For some reason, you guys decided to swap "close" and "open".**

**This swap has a massive affect on the entire mechanism**. I'll explain:
1. In the real world, *tomorrows* 'open' price is pretty close to *today's* 'close' price. Well, in-fact we can pretty much guess the 'open' price based on the 'close' price.
2. The code (modal, backtesting, etc) assumes 'close' is in index [0]. **But index [0] holds the 'open' price**.
```python
    def __get_matrix_y(self):
        return self.__test_set["y"][self._steps, 0, :]
```
From [https://github.com/Vanint/PPN/blob/master/pgportfolio/trade/backtest.py](https://github.com/Vanint/PPN/blob/master/pgportfolio/trade/backtest.py#L66). Note the [0].
3. Instead of calculating the relative 'close' price, what is calculated is the **relative 'open'** prices!
4. The model (neural net) gets the input of `shape=(num_features, num_stocks, window_size)`.
- Now let's run the model and think what it does... The model **knows** today's both 'open' and 'close' values (also 'high' and 'low') - and should theoretically conclude and "guess" the allocation based on the fact that we are tested on *tomorrows* 'close'.
- Since in-fact the model is trained on the **relative 'open'** prices, rather that 'close' -- The model just puts all the weight on the individual stock that its 'close' price is distant from its 'open' price - why? due to what I've mentioned in (1).
5. I indeed reproduced the performance on SP500, but after "fixing" the code and removing this line - everything broke-up.

**Conclusion: Calculating relative 'open' prices, together with providing the 'close' data of the last day -- leaks the approximate best allocation**

If you could reproduce **correctly** your paper, that would be great.

Sincerely,
Natan

**Comment by Vanint** [comment]
Hi, thanks for your attention. 
1. Yes. It is better for choosing features = ['close', 'high', 'low', 'open'] on SP500. In this setting, it is harder to adjust the algorithm. For the engineering purpose, you can try (Only TCN + the second decision-making mechanism + test_proportion 0.1) or (Only TCN + the third decision-making mechanism + test_proportion 0.2/0.3). They seem to work in engineering.
2. Also, you can try the cryptocurrecny datasets.

**Comment by NatanBagrov** [comment]
> Hi, thanks for your attention.
> 
> 1. Yes. It is better to choose features = ['close', 'high', 'low', 'open'] on SP500. In this setting, it is harder to adjust the algorithm. For the engineering purpose, you can try (Only TCN + the second decision-making mechanism + test_proportion 0.1) or (Only TCN + the third decision-making mechanism + test_proportion 0.2/0.3). They seem to work in engineering.
> 2. Also, you can try the cryptocurrecny datasets.

1. You're missing the fact that this is not an option, and this choice is illegal and called cheating. By doing this there is a leak and the algorithm "knows" the future. It is not allowed in simulated trading.

**Comment by Vanint** [comment]
Yes, it is right to use ['close', 'high', 'low', 'open'] on SP500. When you implement it, you can do as you thought.
